[package]
name = "clean-that-rust"
version = "0.1.0"
authors = ["Thomas Kiley <thekileyenator@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
actix-web = "2.0"
actix-rt = "1.0"